### ISSUE TITLE
Code Error to be corrected

### ISSUE THREAD

**Issue by serre20** [zhyliu00/TPB#1]
There is something wrong in your code.
When I try to run the code, the following problem could not be eliminated:

```
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    model_loss ,mse_loss, rmse_loss, mae_loss, mape_loss = rep_model.meta_train_revise(data_spt, matrix_spt, data_qry, matrix_qry)
  File "/root/autodl-nas/TPB/./model/Meta_Models/rep_model_final.py", line 251, in meta_train_revise
    out, y, meta_graph = self.model(data_spt[i], A_gnd)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-nas/TPB/./model/Meta_Models/rep_model_final.py", line 114, in forward
    raw_emb, Ax = STmodel(raw_x,A_list)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-nas/TPB/./model/Meta_Models/reconstruction.py", line 384, in forward
    gate = self.gate_convs[i](residual)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 298, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [16, 32, 207, 13]
```

Your work is extremely valuable to me. I would greatly appreciate it if you could make an effort to resolve the bug.

**Comment by zhyliu00** [comment]
I think you have a different pytorch version. Maybe `nn.Conv1d` can not take the four-dimension tensor as input in your pytorch.

**Comment by serre20** [comment]
It really works! Thank you for your help!
